apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: neodash
  namespace: ai-platform
spec:
  ingressClassName: traefik
  rules:
    - host: neodash.kernow.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: neodash
                port:
                  number: 5005
