apiVersion: v1
kind: Service
metadata:
  name: neodash
  namespace: ai-platform
  labels:
    app: neodash
    component: visualization
spec:
  type: ClusterIP
  selector:
    app: neodash
  ports:
    - name: http
      port: 5005
      targetPort: 5005
