apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-platform

resources:
  - infisical-secret.yaml
  - db-init-job.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - robots-txt.yaml
