apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - infisical-secret.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - nodeport-service.yaml
  - ingress.yaml
