apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-platform
resources:
  - infisical-secrets.yaml
  - netbox-postgresql.yaml
  - netbox-deployment.yaml
  - netbox-bootstrap.yaml
  - netbox-seed-devices.yaml
  - network-discovery.yaml
  - unifi-discovery.yaml
