apiVersion: v1
kind: Service
metadata:
  name: silverbullet
  namespace: ai-platform
  labels:
    app: silverbullet
spec:
  type: NodePort
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 31116
  selector:
    app: silverbullet
