apiVersion: v1
kind: Service
metadata:
  name: silverbullet
  namespace: ai-platform
  labels:
    app: silverbullet
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: silverbullet
