apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: langgraph
  namespace: ai-platform
spec:
  ingressClassName: traefik
  rules:
    - host: langgraph.agentic.kernow.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: langgraph
                port:
                  number: 8000
