apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kernow-io-wildcard
  namespace: cert-manager
spec:
  secretName: kernow-io-tls
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "vikunja,traefik,keep,ai-platform"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "vikunja,traefik,ai-platform,keep"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - kernow.io
    - "*.kernow.io"
