apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-platform

resources:
  - configmap.yaml
  - context-configmap.yaml
  - deployment.yaml
  - infisical-secret.yaml

commonLabels:
  app.kubernetes.io/name: gemini-agent
  app.kubernetes.io/component: agent
  app.kubernetes.io/part-of: ai-platform
