---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - cronjob.yaml

commonLabels:
  app.kubernetes.io/name: pattern-detector
  app.kubernetes.io/component: learning-system
