apiVersion: v1
kind: Service
metadata:
  name: openwebui
  namespace: ai-platform
  labels:
    app.kubernetes.io/name: openwebui
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: openwebui
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: 31120
      protocol: TCP
