apiVersion: v1
kind: Service
metadata:
  name: keep-frontend
  namespace: keep
  labels:
    app.kubernetes.io/name: keep
    app.kubernetes.io/component: frontend
spec:
  type: NodePort
  ports:
    - name: http
      port: 3000
      targetPort: http
      nodePort: 31106
      protocol: TCP
  selector:
    app.kubernetes.io/name: keep
    app.kubernetes.io/component: frontend
