apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: keep-secrets
  namespace: keep
  labels:
    app.kubernetes.io/name: keep
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical-operator-system
      secretsScope:
        projectSlug: agentic-platform-mszn
        envSlug: prod
        secretsPath: /keep
  managedSecretReference:
    secretName: keep-secrets
    secretNamespace: keep
    secretType: Opaque
    creationPolicy: Owner
