apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keep
  namespace: keep
  labels:
    app.kubernetes.io/name: keep
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: keep.kernow.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keep
                port:
                  number: 8080
