apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keep

resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml
