apiVersion: v1
kind: Namespace
metadata:
  name: keep
  labels:
    app.kubernetes.io/name: keep
    app.kubernetes.io/part-of: alerting
    # Allow init container to run as root for volume permission fix
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
