apiVersion: v1
kind: Service
metadata:
  name: keep
  namespace: keep
  labels:
    app.kubernetes.io/name: keep
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: 31105
      protocol: TCP
  selector:
    app.kubernetes.io/name: keep
    app.kubernetes.io/component: server
