apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: traefik-pool
spec:
  blocks:
    - cidr: 10.20.0.90/32   # Single IP for Traefik
  serviceSelector:
    matchLabels:
      io.cilium/lb-ipam-ips: "traefik"
