# SealedSecret for Infisical Operator Bootstrap Credentials
# Encrypted with cluster-specific sealing key - safe to commit to git
# Only decryptable by the sealed-secrets controller in the agentic cluster
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: universal-auth-credentials
  namespace: infisical-operator-system
spec:
  encryptedData:
    clientId: AgCDgM0XTNpd74VguH+UtwGpCdN908wvY2kNWynapR4xMIcD8yDEgBTB8/l4RQU9bgfWXRXkMyGoXNHAd3JHicRMLaX6370vzzhbrdMzij1M/ZlhnPrfL/LuXF7V0VrvkRI58OE6d2J4SwdvNku5zgIX4zhor+e3m/rFTs0yw1zT4YDA6mvT6nmjza3+tRky1DKeGmWNks8JcCsTGSSrukMyAcVIEsoIVkCMe8bixN7ciS8DmTkNyCTf08Fd+0gIUzmPGW7zrlcjAMHaTi0mxFci/uiqKsRJZZkbgBoK5IxV824IVuPhtlMGaxqTvctfqeca9kCfSkL2U9Ka989V6n3bd74n360IrjyTT93rMYCPxe8kLXOc6gfJByXHwY78yKDh2CPqkLZ37VFjStsLaQG+kuZiqPoOw5QUR86PXgG08Tg8UNIpexgBDc/Vw1zoblXgSeohZbYcJcYOEtRS1Gk//pny46ZfEixTCNgwG+fIs9CDiV7no0zM6dWgtz63/k+0gMzHaBAKndF8FmVA2PowbcgHg9y/LIG/BsffIGreaFlQtzI3idqBE5vpF49e61G4pJGOlCeT9Tf8wxOgvE/czC8ukZqy4rG2NTUmtFLXA6Fvk3CCbPfy4x5JpIb5cNLo8eLL1qwUKxGUiwj6o/cAM5lwJuSelJG2bxywUU/Ur5qk+lAjlrfl10z6Zmz+qhmCsFx0S1BUc70QlAmRnUzQEttuwAlJwKNyB744unFfwa1jVYw=
    clientSecret: AgAwGNNGK+6/+uz+PWHwL0kVq3B5DbHHLNa54i2Q2WlL13rbfHoQOyJQ0E2Xf5QVCOC/C+m3bFAn/hcjMJNQf4RjAtpiLYxGYH8rLfnuNpvrjbg+g+pFI/M5iIT+kZ4XkzXr6cYJJZduGhLIuQfJgYPRnVAQYlchgK5jxmepGlxrAsT4gBc6QlfOzJno9dBGP5gW2bJXybrVCrGUanZidRF0lEDkakLZ9gtJ494EIxchBhmVPqcdq5ItGavxpjdANqrXwtiNsH1MZjePmHfSensdUVKO9Ma+pcWJpPW7PLzcsaWQvCScr6vJLNgpdqbmXt6kfMxDRaiTzQ61mmYdBerLDi160EzXQ/JYCIyEBAq/L5YgX0FzGVgP747b+ZeV52lBEkXAVBJgb5KmRuT14Yrr1vitIUsUevlSLRCsJCJ1RjCQl3Q68HzKz7MPq11TkkezJxzkROKL7wmjrsojDzaQahbJhTkijyAxnAFFFPpLUTX/xmJtHAz6Cw1FPPyWfhty5Y2t8ofXi92MoAiqI3zGoE4a8E5HDnE4Duir8AFohv9wIuDiD3WswZOuYlCLfsIy31xE0GM6Q9BhDj4HcLCEXW9hfuWahW9YhOVYrsv/PepEwWbQLE5zglp7YVye5cJrU3/1/2hBA1h2MJkY1iShuqem4nJXER9oeenNh0vUwVhxC7EbZD0NmSXMk1VqsJhsuRRA4RE20S5U5urXkLnd1fpHhT423H9SayQTYGvC5x3v+2BD77icx26TTFFGYWKJmMBT6yqovhrFC005lRBl
  template:
    metadata:
      name: universal-auth-credentials
      namespace: infisical-operator-system
    type: Opaque
