apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-platform

resources:
  - infisical-secrets.yaml
  - configmap.yaml
  - deployment.yaml
  - ingress.yaml
  - cronjob.yaml
